### ISSUE TITLE
error Cannot import a null node.

### ISSUE THREAD

**Issue by miladmeh** [anastra13/nsx-v_to_nsx-t#1]
Hi Thanks for the script. but when I run this I get following error.
I have an ORG and I need to migrate a vAPP from one OVDC to another OVDC which are mapped to different PVDCs
The vMotions are enabled. on all the servers. 
There is a test vApp inside OVDC1 (source) with one VM and it is attached to 2 VLAN Portgroups. (1 vAPP network and one OVDC Network) 
Exception calling "ImportNode" with "2" argument(s): "Cannot import a null node."
At C:\Users\test\Downloads\nsx-v_to_nsx-t.ps1:137 char:5
+     $NetworkConnectionSection = $XML_body.importnode($VM_request.Netw ...

Can you please help ?

**Comment by anastra13** [comment]
I think you need to enable the ‘Share this network with other VDCs in this organization’ option on each network. All Networks > NetworkName (Edit: ‘Shared’)
![Capture d’écran 2024-11-14 à 13 31 32](https://github.com/user-attachments/assets/272e0d22-fc17-47eb-bf15-faf47af79a67)
